name: AncientGates
version: 1.5
main: org.mcteam.ancientgates.Plugin
commands:
  gate:
    description: All of the Ancient Gates commands
    usage: See documentation.
permissions:
  ancientgates.admin:
    description: Allows the use of Ancient Gates commands
    default: false
